<?php

/**
 * PluginsfAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfAssetTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginsfAssetTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('PluginsfAsset');
  }
  
  /**
   * check if file exists in folder
   * @param  integer $folderId
   * @param  string  $filename
   * @return boolean
   */
  public function exists($folderId, $filename)
  {
    $query = $this->createQuery()
      ->where('folder_id = ?', $folderId)
      ->andWhere('filename = ?', $filename);

    return $query->count() > 0 ? true : false;
  }
  
  /**
   * Retrieves a sfAsset object from a relative URL like
   *    /medias/foo/bar.jpg
   * i.e. the kind of URL returned by $sf_asset->getUrl()
   */
  public  function retrieveFromUrl($url)
  {
    $url = sfAssetFolderTable::getInstance()->cleanPath($url, '/');
    list($relPath, $filename) = sfAssetsLibraryTools::splitPath($url, '/');
    $query = $this->createQuery('a')
      ->where('filename = ?', $filename)
      ->leftJoin('a.Folder f')
      ->andWhere('f.relative_path = ?', $relPath ?  $relPath : null)
      ;
    return $query->fetchOne();
  }
  
}