<?php

/**
 * PluginsfAssetFolderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfAssetFolderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfAssetFolderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfAssetFolder');
    }
    
    /**
     * Retrieves folder by relative path
     *
     * @param string $path
     * @param string $separator
     * @return sfAssetFolder
     */
    public function retrieveByPath($path = '', $separator = DIRECTORY_SEPARATOR)
    {
      $path = $this->cleanPath($path, $separator);
      $query = $this->createQuery()->where('relative_path = ?', $path ? $path : null);
      
      return $query->fetchOne();
    }
    
    /**
     * Sanitize path
     *
     * @param  string $path
     * @param  string $separator
     * @return string
     */
    public function cleanPath($path, $separator = '/')
    {
      $path = trim($path, $separator);
      $root_name = sfConfig::get('app_sfAssetsLibrary_upload_dir', 'media');
      if (!$path)
      {
        $path = $root_name;
      }
      elseif (strpos($path, $root_name) !== 0)
      {
        $path = $root_name . $separator . $path;
      }
  
      return $path;
    }
    
    /**
     * Recursively creates parent folders
     *
     * @param string $path
     * @return sfAssetFolder
     */
    public function createFromPath($path)
    {
      $path = self::cleanPath($path, DIRECTORY_SEPARATOR);
      list($parent_path, $name) = sfAssetsLibraryTools::splitPath($path);
      if (!$parent_folder = $this->retrieveByPath($parent_path))
      {
        $parent_folder = $this->createFromPath($parent_path);
        $parent_folder->save();
      }
      $folder = new sfAssetFolder();
      $folder->setName($name);
      $folder->setRelativePath($path);
      $folder->getNode()->insertAsLastChildOf($parent_folder);
      $folder->save();
  
      return $folder;
    }
}